# Generated by Django 3.1.3 on 2022-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
