# Generated by Django 3.1.3 on 2022-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_dress_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='pic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
